# Generated by Django 4.2.1 on 2023-05-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 14, 19, 8, 649527, tzinfo=datetime.timezone.utc)),
        ),
    ]
