# Generated by Django 4.1.7 on 2023-04-04 09:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 4, 4, 9, 46, 4, 316115, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 9, 46, 4, 316083, tzinfo=datetime.timezone.utc)),
        ),
    ]
