# Generated by Django 4.1.7 on 2023-04-04 10:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0004_alter_message_expires_at_alter_message_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 9, 
                                                                 59, 53, 817370, 
                                                                 tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, 
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
