# Generated by Django 4.2 on 2023-04-19 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webchatapp', '0007_alter_message_expires_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserKey',
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 23, 25, 889127, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
