# Generated by Django 4.2 on 2023-04-24 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0008_rename_user_userkey_alter_message_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkey',
            old_name='key',
            new_name='privateCryptedKey',
        ),
        migrations.AddField(
            model_name='userkey',
            name='publickey',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 37, 4, 729637, tzinfo=datetime.timezone.utc)),
        ),
    ]
