# Generated by Django 4.2 on 2023-04-25 12:58

import datetime
from django.db import migrations, models
import webchatapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0011_userkey_salt_alter_message_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, validators=[webchatapp.models.validate_message_content]),
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 12, 58, 8, 787183, tzinfo=datetime.timezone.utc)),
        ),
    ]
