# Generated by Django 4.1.7 on 2023-04-04 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0002_message_sent_at_alter_message_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 9, 56, 51, 823341, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 4, 4, 9, 56, 51, 823374, tzinfo=datetime.timezone.utc)),
        ),
    ]
