# Generated by Django 4.2 on 2023-04-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0006_alter_message_expires_at_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 19, 37, 612472, tzinfo=datetime.timezone.utc)),
        ),
    ]
