# Generated by Django 4.2 on 2023-04-24 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0009_rename_key_userkey_privatecryptedkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkey',
            old_name='publickey',
            new_name='publicKey',
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 1, 32, 910311, tzinfo=datetime.timezone.utc)),
        ),
    ]
