# Generated by Django 4.2 on 2023-04-25 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatapp', '0010_rename_publickey_userkey_publickey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='salt',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 11, 7, 53, 846671, tzinfo=datetime.timezone.utc)),
        ),
    ]
